api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ObrazekViewSet,UserProfileViewSet

router = DefaultRouter()
router.register('obrazek', ObrazekViewSet, basename='Obrazek')
router.register('profile',UserProfileViewSet , basename='Obrazek')

urlpatterns = [
    path('', include(router.urls))

]

galeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

# static file
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import RedirectView

from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('widok.urls')),
    path('api/', include('api.urls')),

    # path('favicon.ico', RedirectView.as_view(url='/media/favicon.ico')),
    path("register/", user_views.rejestracja, name='register'),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path("logout/", user_views.logout_user, name='logout'),
    path("profile/", user_views.profile, name='profile'),
    path('kontakt/', user_views.contact, name='contact'),

    # reset hasla
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

widok/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', views.PhotoListView.as_view(), name='index'),
    path('user/<str:username>', views.UserPostView.as_view(), name='user-posts'),

    path('obrazek/<int:pk>/', views.ObrazekDetailView.as_view(), name='detail'),

    path('add/<str:opcja>', views.add, name='add'),

    path('obrazek/<int:id_obrazka>/edit/', views.edit, name='edit'),
    path('obrazek/<int:pk>/delete/', views.PostDeleteView.as_view(), name='remove'),

]

widok/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
import statistics


class Obrazek(models.Model):
    obrazek_path = models.CharField(max_length=200, null=True, default=None)
    obrazek_file = models.ImageField(upload_to='img_file', null=True, default=None)

    tytul = models.CharField(max_length=200)
    data_publikacji = models.DateTimeField(default=timezone.now)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.tytul

    def srednia_ocen(self):
        if oceny := self.oceny_set.all():
            avg = sum([x.ocena for x in oceny]) / oceny.count()
            return round(avg, 1)
        return 0


class Kometarz(models.Model):
    obrazek = models.ForeignKey(Obrazek, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    tresc = models.TextField(max_length=320)
    data_publikacji = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.tresc}_do obrazka_{self.obrazek.id}"


class Oceny(models.Model):
    obrazek = models.ForeignKey(Obrazek, on_delete=models.CASCADE)
    ocena = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.autor}_ocena: {self.ocena}_obrazka: {self.obrazek.tytul}"

widok/forms.py
from django import forms
from .models import Obrazek, Oceny, Kometarz
from django.contrib.auth.models import User


class Add_obrazek_link(forms.ModelForm):
    class Meta:
        model = Obrazek
        fields = ['obrazek_path', 'tytul']
        widgets = {
            'obrazek_path': forms.TextInput(attrs={'class': 'form-control col-md-12', 'placeholder': 'https://...'}),
            'tytul': forms.TextInput(attrs={'class': 'col-12 col-md-7 col-lg-6 form-control'})
        }


class Add_obrazek_file(forms.ModelForm):
    class Meta:
        model = Obrazek
        fields = ['obrazek_file', 'tytul']
        widgets = {

            'tytul': forms.TextInput(attrs={'class': 'col-12 col-md-7 col-lg-6 form-control'})
        }

widok/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Obrazek
from .forms import Add_obrazek_link, Add_obrazek_file
from .utils import link_check

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DeleteView,DetailView,View


from django.contrib.auth.models import User

from django.core.cache import cache



# główny widok
ilosc_obrazkow_na_strone = 9


class PhotoListView(ListView):
    model = Obrazek
    template_name = 'widok/home.html'
    paginate_by = ilosc_obrazkow_na_strone

    def get_queryset(self):
        queryset = Obrazek.objects.all().prefetch_related('kometarz_set', 'oceny_set').order_by('-data_publikacji')

        return cache.get_or_set('obrazy', queryset, 500)
        # return queryset

# lista uzytkownika

class UserPostView(ListView):
    model = Obrazek
    template_name = 'widok/home.html'

    paginate_by = ilosc_obrazkow_na_strone

    def get_queryset(self):
        user = get_object_or_404(User.objects.select_related('profile'), username=self.kwargs.get('username'))
        self.kwargs['img'] = user.profile.image.url
        queryset = Obrazek.objects.filter(autor=user).order_by('-data_publikacji').prefetch_related('kometarz_set',
                                                                                                    'oceny_set')
        return cache.get_or_set(f'obrazy_user{user.id}', queryset, 100)
        # return queryset


# Usuwanie
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Obrazek
    success_url = '/'

    def test_func(self):
        obrazek = self.get_object()
        return self.request.user == obrazek.autor or self.request.user.is_superuser



# Dodawanie obrazka
@login_required
def add(request, opcja):
    if request.method == 'POST':

        form = Add_obrazek_link(request.POST) if opcja == 'link' else Add_obrazek_file(request.POST, request.FILES)

        if form.is_valid():
            obrazek = form.save(commit=False)

            link_ok = link_check(obrazek.obrazek_path) if opcja == 'link' else [True]

            if link_ok[0]:

                obrazek.data_publikacji = timezone.now()
                obrazek.autor = request.user

                obrazek.save()

                return redirect("detail", pk=obrazek.pk)
            else:
                messages.error(request, link_ok[1])
                return render(request, 'widok/form.html', {'form': form, 'przycisk': 'Dodaj', 'opcja': opcja})

    else:
        form = Add_obrazek_link if opcja == 'link' else Add_obrazek_file
    return render(request, 'widok/form.html', {'form': form, 'przycisk': 'Dodaj', 'opcja': opcja})


# edycja
@login_required
def edit(request, id_obrazka: int):
    obrazek = get_object_or_404(Obrazek, pk=id_obrazka)
    old_path = obrazek.obrazek_path

    if request.user == obrazek.autor or request.user.is_superuser:

        if request.method == 'POST':

            form = Add_obrazek_link(request.POST, instance=obrazek) if obrazek.obrazek_path else Add_obrazek_file(
                request.POST, request.FILES, instance=obrazek)  # wprowadza istniejace dane

            if form.is_valid():
                link_ok = link_check(obrazek.obrazek_path) if obrazek.obrazek_path else [True]
                if link_ok[0]:

                    obrazek = form.save(commit=False)

                    obrazek.data_publikacji = timezone.now()
                    obrazek.save()

                    if obrazek.obrazek_path != old_path:
                        obrazek.oceny_set.all().delete()

                    return redirect('detail', pk=obrazek.id)
                else:
                    messages.error(request, link_ok[1])
                    return redirect('edit', pk=obrazek.id)

        else:
            form = Add_obrazek_link(instance=obrazek) if obrazek.obrazek_path else Add_obrazek_file(instance=obrazek)

        return render(request, 'widok/form.html', {'form': form, 'przycisk': 'edytuj post', 'obrazek': obrazek})

    else:
        messages.error(request, "Nie masz uprawnień do tej operacji")
        return redirect('detail', pk=obrazek.id)




class ObrazekDetailView(DetailView):
    queryset = Obrazek.objects.select_related('autor', 'autor__profile')
    template_name = 'widok/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        czy_ocenil = 0
        if user.id:
            if ocena := self.object.oceny_set.filter(autor=user):
                czy_ocenil = ocena[0].ocena

        context['czy_ocenil'] = czy_ocenil
        context['podglad_gwiazdek'] = [5, 4, 3, 2, 1]
        return context

widok/templates/widok/detail.html
{%extends 'base.html'%}
{%block content%}
{% load static %}
{% load cache %}

<link rel="stylesheet" href="{%static 'css/ikony.css'%}">
<link rel="stylesheet" href="{%static 'css/star.css'%}">
<div class="container">



    <div class="row d-flex justify-content-between">
        <a id="back" onclick="window.history.back()" class="btn  btn-lg">
            <i class="fas fa-arrow-left"></i>

        </a>
        <div>
            {% if user == obrazek.autor or user.is_superuser%}
            <!--        edycja-->
            <a class="btn edit btn-lg" href="{%url 'edit' obrazek.id%}">
                <i class="fas fa-edit"></i>
            </a>
            <!--        usuwanie-->
            <a class="btn bin btn-lg" href="{%url 'remove' obrazek.id%}">

                <i class="fas fa-trash-alt"></i>

            </a>
            {%endif%}
        </div>
    </div>
    <p>
        {%if messages%}
        {%for message in messages%}
    <div class="alert {%if message.tags == 'error'%}alert-danger {%else%}alert-{{message.tags}}{%endif%} alert-dismissible"
         role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{message}}
    </div>
    {%endfor%}
    {%endif%}
    </p>



    <div class="row text-right d-md-none ">
        <small class="text-muted col-12">Data publikacji: {{ obrazek.data_publikacji|date:"F d Y" }}</small>
    </div>

    <!--    zdjecie-->
    <div class="card">
        <img

                {%if obrazek.obrazek_path%}
                src="{{obrazek.obrazek_path}}"
                {%else%}
                src="{{obrazek.obrazek_file.url}}"
                {%endif%}

                min-width="1024px" min-height="768px" class="card-img-top">

        <div class="card-body" id="ocena">
            <div class="row d-flex justify-content-between ">
                <div class="col-12 col-md-6">
                    <a style="text-decoration:none;" href="{%url 'user-posts' obrazek.autor %}">
                        <img class="rounded-circle" src="{{obrazek.autor.profile.image.url}}" width="32px"
                             height='32px'>
                        {{obrazek.autor}}
                    </a>
                </div>
                <div class="col-12 col-md-6 text-md-right ">
                    <small class="text-muted d-none d-md-block">Data publikacji: {{ obrazek.data_publikacji|date:"F d Y" }}</small>
                </div>
            </div>
            <div class="row p  justify-content-between">
                <div class="col-12 col-md-6 h1">Tytuł: {{obrazek.tytul}}</div>


                <div class="col-12 col-lg-6 text-lg-right podglad_ocen">
                    <!--                    średnia gwiazdek w podglądzie-->


                    <span class="font-weight-light  h4">
                    </span>
                </div>
            </div>

            <div name="star">
                {%if user.is_authenticated %}
                {%if czy_ocenil%}
                <div class="row h5  pt-4">
                    <div class="col">
                        <div class="rating ">
                            {%for i in podglad_gwiazdek%}
                            <input type="radio"
                                   {%if i == czy_ocenil %} checked {%endif%}><label class="disabled"></label>
                            {%endfor%}
                        </div>
                    </div>
                </div>

                <button type="submit" class="  mb-1 ml-1 btn btn-primary " disabled>ocenione</button>
                {%else%}
                <!--Onecianie-->


                <div class="row h5  pt-4">
                    <div class="col">
                        <div class="rating ">

                            <input type="radio" name="ocena" value="5" id="id_ocena_0">
                            <label for="id_ocena_0">1 stars</label>

                            <input type="radio" name="ocena" value="4" id="id_ocena_1">
                            <label for="id_ocena_1">2 stars</label>

                            <input type="radio" name="ocena" value="3" id="id_ocena_2">
                            <label for="id_ocena_2">3 stars</label>

                            <input type="radio" name="ocena" value="2" id="id_ocena_3">
                            <label for="id_ocena_3">4 stars</label>

                            <input type="radio" name="ocena" value="1" id="id_ocena_4">
                            <label for="id_ocena_4">5 stars</label>

                        </div>


                    </div>
                </div>

                <button type="submit" class=" wyslij_ocene ml-1 btn btn-primary">Wyślij ocene</button>
                {%endif%}


                {%else%}
                <div class="pt-4 pb-4">
                    <a href="{% url 'login' %}?next={{request.path}}"> Zaloguj się</a> aby dodać ocene
                </div>
                {%endif%}
            </div>
        </div>
    </div>
    <!--    sekcja kometarzy-->
    <div class="row d-flex justify-content-center">
        <p class="h1  alert alert-light" id="komentarz">Sekcja komentarzy</p>
    </div>
    <!--    WYSWIETLANIE-->
    <div class="d-flex  justify-content-center">
        <div class="jumbotron pt-5 pb-5 col-12">
            <div class="col-12">
                <div class="row bootstrap snippets bootdeys">
                    <div class="col-md-8 col-12">
                        <div class="comment-wrapper">
                            <div class="panel panel-info">
                                <div class="panel-heading h3">
                                    Dodaj komentarz
                                </div>
                                <hr>
                                <div class="panel-body">
                                    {%if user.is_authenticated%}
                                    
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label>Autor:</label>

                                            <div class="h2">
                                                <img class="rounded-circle" src="{{user.profile.image.url}}"
                                                     width="32px" height='32px'> {{user}}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Treść komentarza</label>
                                            <textarea class="col-11 pole_kom form-control" rows="3"
                                                      placeholder="twój komentarz..."></textarea>
                                        </div>
                                        <button class="dodaj_kom btn btn-primary">dodaj</button>
                                    
                                    {%else%}
                                    <p class="mt-5 mb-5"><a href="{% url 'login' %}?next={{request.path}}">
                                        Zaloguj się</a> aby dodać komentarz</p>
                                    {%endif%}
                                    <div class="clearfix"></div>
                                    <hr>
                                    <!--                                        Sekcja kometarzy-->
                                    <ul class="media-list pl-0">

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- tymczasowe -->

<script>
    const link_values = window.location.href.slice(0, -1).split('/')
    const obrazek_id = link_values[link_values.indexOf('obrazek')+1]


    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
</script>


<script src="{%static 'js/detail_gwiazdki.js'%}"></script>
<script src="{%static 'js/detail_kometarze.js'%}"></script>


{%endblock%}

widok/templates/widok/form.html
{%extends 'base.html'%}
{%block content%}
{% load static %}

<div class="container">
    {%if messages%}
    {%for message in messages%}
    <div class="alert {%if message.tags == 'error'%}alert-danger {%else%}alert-{{message.tags}}{%endif%} alert-dismissible"
         role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{message}}
    </div>
    {%endfor%}
    {%endif%}


    <a class="btn  btn-lg" href=" {%if obrazek.id%} {%url 'detail' obrazek.id%} {%else%} / {%endif%}">
        <i class="fas fa-arrow-left"></i>
    </a>
    <div>

        <div class="jumbotron">
            <div class="row">

                <h1 class="display-5 col-12">{%if obrazek.id%}Edytuj obraz{%else%}Dodaj obraz do galerii{%endif%}</h1>


            </div>
            <hr class="my-4">
            <!--    form-->
            <div class="row">


                <form class="col-12 row" method="post" enctype="multipart/form-data">{% csrf_token %}


                    <div class="col-md-8">
                        <div class="form-group">
                            {%if obrazek.obrazek_path or opcja == 'link'%}
                            <label for="id_obrazek_path">Ścieżka do obrazka</label>

                            {{form.obrazek_path}}
                            <small class="text-muted">Link musi być bazpieczny oraz obrazek musi mieć nie mniej niż
                                640x480</small>
                            {%else%}

                            {{form.obrazek_file}}

                            {%endif%}

                        </div>

                        <div class="form-group ">
                            <label for="id_tytul">Tytuł</label>
                            {{form.tytul}}
                        </div>
                    </div>

                    <div id="podglad" class="col-12 col-xl-4 pb-4">

                        {%if not obrazek%}
                        <div id="spin" class=" mt-5 d-flex align-items-center">
                            <strong>Podgląd obrazka... </strong>
                            <div class="spinner-border ms-auto text-primary ml-3" role="status"
                                 aria-hidden="true"></div>
                        </div>
                        <img id="blah" style="max-height:200px; max-width:350px" class="rounded ">
                        {%else%}

                        <img id="blah" src="
                        {%if obrazek.obrazek_path%}
                        {{obrazek.obrazek_path}}
                        {%else%}
                        {{obrazek.obrazek_file.url}}
                        {%endif%}
                        " style="max-height:200px; max-width:350px" class="rounded ">
                        {%endif%}

                    </div>

                    <div class="col-12">
                        <button type="submit" class="btn btn-primary ">{{przycisk}}</button>
                    </div>
                </form>


            </div>

        </div>


    </div>

</div>


<script src="{%static 'js/form.js'%}"></script>

{%endblock%}

widok/templates/widok/home.html
{%extends 'base.html'%}
{%block content%}
{% load static %}


<div class="container" style="height: 100%">
    <!--    info-->
    {%if messages%}
    {%for message in messages%}
    <div class="alert {%if message.tags == 'error'%}alert-danger {%else%}alert-{{message.tags}}{%endif%} alert-dismissible"
         role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{message}}
    </div>
    {%endfor%}
    {%endif%}

    <!--    obrazki-->
    {%if view.kwargs.username%}
    <h1 class="mb-3">Obrazy dodane przez użytkownika: <img class="rounded-circle" src="{{view.kwargs.img}}" width="50px"
                                                           height="50px" class="mr-2"/> {{view.kwargs.username}}
        ({{page_obj.paginator.count}})</h1>
    <hr>
    {%endif%}


    <div class="row pt-3 allobr">


        {%for obrazek in object_list %}
        <figure class="col-md-6 col-lg-4">
            <a href="{%url 'detail' obrazek.id%}">
                <div class="obr obr_r">
                    <img
                            {%if obrazek.obrazek_path%}
                            src="{{obrazek.obrazek_path}}"
                            {%else%}
                            src="{{obrazek.obrazek_file.url}}"
                            {%endif%}
                            style="height:100%; width:100%"
                            class="img-fluid zdjecie rounded ">
                </div>
            </a>
            <div class="obr-bottom">
                <div class="bottom-left ">&#11088;: {{obrazek.srednia_ocen}}<small
                        class="text-muted ml-1">{{obrazek.count}}</small></div>
                {{test}}
                <div class="bottom-right">Komentarze: {{obrazek.kometarz_set.count}}</div>
                <h3 class="text-center my-3 pb-2">{{obrazek.tytul}}</h3>
            </div>
        </figure>

        {%endfor%}


    </div>

    <!--Pagination-->
    {% if is_paginated%}

    <div class="btn-toolbar col-12 d-flex justify-content-between" role="toolbar"
         aria-label="Toolbar with button groups">
        <!--first-->
        <div class="btn-group mr-2 d-none d-md-block" role="group" aria-label="First group">
            <a href="?page=1">
                <button type="button" class="btn btn-outline-primary" {%if not page_obj.has_previous%}disabled{%endif%}>

                    Pierwsza
                    <i class="fas fa-fast-backward"></i>
                </button>
            </a>
        </div>

        <div class="btn-group mr-2 col-md-7 col-lg-6" role="group" aria-label="Second group">
            <!--previous-->
            <a class="btn btn-secondary {%if not page_obj.has_previous%}disabled" {%else%}"href="?page={{page_obj.previous_page_number}}{%endif%}">
            <i class="fas fa-step-backward"></i>
            Poprzednia</a>

            <!--Near-->
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num%}
            <a class="btn btn-outline-secondary " href="?page={{num}}">{{num}}</a>
            {%elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
            <a class="btn btn-secondary " href="?page={{num}}">{{num}}</a>
            {%endif%}
            {%endfor%}

            <!--next-->
            <a class="btn btn-secondary {%if not page_obj.has_next%}disabled" {%else%}"
            href="?page={{page_obj.next_page_number}}" {%endif%}>Następna
            <i class="fas fa-step-forward"></i>
            </a>

        </div>
        <!--last-->
        <div class="btn-group d-none d-md-block" role="group" aria-label="Third group">
            <a href="?page={{page_obj.paginator.num_pages}}">
                <button type="button" class="btn btn-outline-primary" {%if not page_obj.has_next%}disabled{%endif%}>
                    <i class="fas fa-fast-forward"></i>
                    Ostatnia
                </button>
            </a>
        </div>


    </div>


    {%endif%}

    <!--end container-->
</div>


<footer id="footer" class="page-footer bottom col-12 footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center  col-12 py-3">© 2021 Copyright
        <span style="color: #007bff;"> Jakub Biernacki</span>
    </div>

    <!-- Copyright -->
</footer>


<!--animacja-->


{%endblock%}

widok/templates/widok/obrazek_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Usuwanie obrazka</legend>
            <div class="row">
                <div class="col-12 col-md-6">
                    <h2>Jesteś pewien że chcesz usunąć zdjecie "{{object.tytul}}" wraz ze wszystkimi ocenami i
                        komentarzami?</h2>
                </div>
                <div class="col-12 col-md-6">
                    <img
                            {%if object.obrazek_path%}
                            src="{{object.obrazek_path}}"
                            {%else%}
                            src="{{object.obrazek_file.url}}"
                            {%endif%}

                            style="height:200px; " class=" rounded ">
                </div>

            </div>

        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Tak, usuń</button>
            <a class="btn btn-outline-secondary" href="{%url 'detail' object.id%}">Anuluj</a>
        </div>
    </form>

</div>
{% endblock content %}